<!-- subcribe -->
<div class="block block-subscribe" style="width: 310px; float: right;margin-top: 20px;">
    <div id="feedback" style="display:none" class="mini-newsletter">
        Thank you for subscribing to our newsletter! 
    </div>
    <form name="newsletter-form" id="newsletter-form" method="post" > 
        <div class="block-content" style="text-align: left;  ">
            <input  type="text" placeholder="Email address" name="email" id="newsletter" title="<?php echo $this->__('Subscribe to Our Newsletter') ?>" class="required-entry input-subscribe" style="width:178px;" />

            <button type="button" title="<?php echo $this->__('Subscribe') ?>"  id="subcribe" class="button">
                <span><span>Subscribe</span></span>
            </button>
            <span class="news-loader" id="news-loader" style="text-align:center; display:none; ">
                <img src="<?php echo Mage::getBaseUrl('media'); ?>mymedia/load2.gif" width="20"/>
                <!--Loading...-->
            </span> 
            <div class="error-news-msg" id="error-news-msg" style="display:none;">Please enter a valid email address.</div>
        </div>
    </form>    
</div> 
<!-- subcribe -->


<script type="text/javascript">        
    //ajax send mail
    jQuery("#subcribe").click(function()
    {    
        var form_email = jQuery('#newsletter').val();
        if(echeck(form_email))
        {
            jQuery.ajax({
                type:'POST',
                url:'<?php echo $this->getUrl('newsletter/subscriber/new') ?>',
                dataType:'json',
                data: {email:form_email},
                beforeSend:function(){
                    jQuery('#news-loader').show();
                },
                success:function(){
                    jQuery('#news-loader').hide();
                    jQuery('#newsletter-form').hide();
                    jQuery('#feedback').show();
                },
                error:function(){
                    jQuery('#news-loader').hide();
                    jQuery('#newsletter-form').hide();
                    jQuery('#feedback').show();
                }

            })
               
        }
    })    
    //check validate email
    function echeck(str) {

        var at="@"
        var dot="."
        var lat=str.indexOf(at)
        var lstr=str.length
        var ldot=str.indexOf(dot)
        if (str.indexOf(at)==-1){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.indexOf(at)==-1 || str.indexOf(at)==0 || str.indexOf(at)==lstr){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.indexOf(dot)==-1 || str.indexOf(dot)==0 || str.indexOf(dot)==lstr){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.indexOf(at,(lat+1))!=-1){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.substring(lat-1,lat)==dot || str.substring(lat+1,lat+2)==dot){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.indexOf(dot,(lat+2))==-1){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        if (str.indexOf(" ")!=-1){
            //alert("Invalid E-mail ID")
            goProcedural()
            return false
        }

        return true                    
    }

    function goProcedural()
    {
        Element.show('error-news-msg');
        Element.hide.delay(5, 'error-news-msg');
    }

</script>
