<?php
/**
 * add canonical url if category is mirrored
 */
$urlCurrent = Mage::helper('core/url')->getCurrentUrl();
$categoryMirrored = Mage::getModel('catalog/category')->getCollection()->addAttributeToFilter('mirrored_to');

if(count($categoryMirrored)) {
    $urlCurrent = '';
}
else {
    $categoryMirrored = Mage::getModel('catalog/category')->getCollection()->addAttributeToFilter('mirrored_copy_from_cate');
    if(count($categoryMirrored))
        $urlCurrent = '';
}
if($urlCurrent) {
    echo "<link rel='canonical' href='{$urlCurrent}' />";
}
?>