<?php
/**
 * add canonical url if category is mirrored
 */
$categoryCurrent = Mage::registry('current_category');

if($categoryCurrent->getData('mirrored_to') || $categoryCurrent->getData('mirrored_copy_from_cate')){
    $urlCurrent = Mage::helper('core/url')->getCurrentUrl();
}
else{
    $urlCurrent = '';
}
if($urlCurrent) {
    echo "<link rel='canonical' href='{$urlCurrent}' />";
}
?>