<?php //var_dump($this->dat());die; ?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Featured Products') ?></h3></td>
            <td class="a-right">
            </td>
        </tr>
    </table>
</div>
<?php //if( !$this->isSingleStoreMode() ): ?>
<!--    --><?php //echo $this->getChildHtml('store_switcher');?>
<?php //endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
