<?php
//var_dump($this->getPriceRange());die;
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>

<?php if ($this->canShowBlock()): ?>
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions">
                    <a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
                </div>
            <?php endif; ?>
            <?php if ($this->canShowOptions()): ?>
                <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?><span id="clear-filter-custom"style="display: none;float: right;cursor: pointer">clear</span></p>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters();
                        ksort($_filters);
                    ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount()): ?>
                            <dt><?php echo $this->__($_filter->getName()) ?></dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>


        <p>
            <label for="amount">Price range:</label>
            <input value="$0 - $200" id="amount" style="border:0; color:#f6931f; font-weight:bold;"
                   type="text">
        </p>

        <div class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" id="slider-range">
            <div style="left: 1.6%; width: 26.8%;" class="ui-slider-range ui-widget-header ui-corner-all"></div>
            <span style="left: 1.6%;" class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
            <span style="left: 28.4%;" class="ui-slider-handle ui-state-default ui-corner-all ui-state-focus"
                  tabindex="0"></span>
        </div>

        <?php $aryPrice = explode('-', $_GET['price']); ?>
        <script src="<?php echo Mage::helper('link')->getSkinFrontend();?>js/filter/jquery-ui.js"></script>
        <script src="<?php echo Mage::helper('link')->getSkinFrontend();?>js/filter/filter.js"></script>
        <script>
            //jQuery.noConflict();
<!--            jQuery(document).ready(function () {-->
<!--                jQuery("#slider-range").slider({-->
<!--                    range: true,-->
<!--                    min: 0,-->
<!--                    max: --><?php //echo $this->getPriceRange(); ?><!--,-->
<!--                    values: [ 0, "--><?php //echo $this->getPriceRange(); ?><!--" ],-->
<!--                    slide: function (event, ui) {-->
<!--                        jQuery("#amount").val("$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ]);-->
<!--                        var min = ui.values[0];-->
<!--                        var max = ui.values[1];-->
<!---->
<!--                        var strVar = document.URL;-->
<!--                        var currentPrice = "--><?php //echo $_GET['price']; ?><!--";-->
<!--                        if(strVar.indexOf("?") == -1){-->
<!--                            var url = strVar + '?price=' + min + '-' + max;-->
<!--                        } else {-->
<!--                            if(currentPrice == ''){-->
<!--                                var url = strVar + '&price=' + min + '-' + max;-->
<!--                            } else {-->
<!--                                var minPrice = "--><?php //echo $aryPrice[0]; ?><!--";-->
<!--                                var maxPrice = "--><?php //echo $aryPrice[1]; ?><!--";-->
<!--                                var url = strVar.replace(minPrice, min);-->
<!--                                var url = strVar.replace(maxPrice, max);-->
<!--                            }-->
<!--                        }-->
<!--                        window.history.pushState("GET", '', url);-->
<!--                        jQuery("#slider-range").slider({ disabled: true });-->
<!--                        location.reload();-->
<!--                    }-->
<!--                });-->
<!--                jQuery("#amount").val("$" + jQuery("#slider-range").slider("values", 0) +-->
<!--                    " - $" + jQuery("#slider-range").slider("values", 1));-->
<!--            });-->


            jQuery(document).ready(function () {
                var $ = jQuery;

                $("#slider-range").slider({
                        range: true,
                        min: 0,
                        max: <?php echo $this->getPriceRange(); ?>,
                        values: [ 0, "<?php echo $this->getPriceRange(); ?>" ],
                        slide: function (event, ui) {
                            jQuery("#slider-range").mouseup(function(){
                                jQuery('span.ui-slider-handle.ui-state-default.ui-corner-all').change()
                                jQuery("#amount").val("$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ]);
                                var min = ui.values[0];
                                var max = ui.values[1];
//                                alert(min);
//                                alert(max);
                                var currentPrice = "<?php echo $_GET['price']; ?>";
                                var aryCurrentPrice = {
                                    min: "<?php echo $aryPrice[0]; ?>",
                                    max: "<?php echo $aryPrice[1]; ?>"
                                };
                                console.log(min+' - '+max);
                                //Filter.filter(min, max, currentPrice, aryCurrentPrice);
                            });
                        }
            });
                $("#amount").val("$" + $("#slider-range").slider("values", 0) +
                    " - $" + $("#slider-range").slider("values", 1));
            });
        </script>
    </div>
<?php endif; ?>



