<?php
/**
 * add data to tag head of html: all page
 */
?>

<link rel="stylesheet" href="<?php echo Mage::helper('featured/link')->getSkin();?>css/megamenu.css"/>
<link rel="stylesheet" href="<?php echo Mage::helper('featured/link')->getSkin();?>css/styles_giang.css"/>

<script src="<?php echo Mage::helper('featured/link')->getSkin();?>js/jquery-1.11.1.min.js"></script>
<script>
    jQuery.noConflict();
</script>


<!--Bootstrap Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="<?php /*echo Mage::helper('featured/link')->getSkin();*/?>bootstrap-3.2.0/css/bootstrap.min.css">-->

<!-- Optional theme -->
<!--<link rel="stylesheet" href="<?php /*echo Mage::helper('featured/link')->getSkin();*/?>bootstrap-3.2.0/css/bootstrap-theme.min.css">-->

<!-- Latest compiled and minified JavaScript -->
<!--<script src="<?php /*echo Mage::helper('featured/link')->getSkin();*/?>bootstrap-3.2.0/js/bootstrap.min.js"></script>-->