<?php
/**
 * add data to tag head of html: all page
 */
?>

<link rel="stylesheet" href="<?php echo Mage::helper('link')->getSkinFrontend();?>css/megamenu.css"/>
<link rel="stylesheet" href="<?php echo Mage::helper('link')->getSkinFrontend();?>css/styles_giang.css"/>
<script src="<?php echo Mage::helper('link')->getSkinFrontend(); ?>js/jquery-1.11.1.min.js"></script>
<script src="<?php echo Mage::helper('link')->getSkinFrontend(); ?>js/noConflict.js"></script>
<script>
    jQuery(document).ready(function(){
        jQuery('h2.subtitle').text('');
    });
</script>