<link rel="stylesheet" href="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/css/idangerous.swiper.css"/>
<style>
    .swiper-container {
        width: 660px;
        height: 250px;
        color: #fff;
    }
    .red-slide {
        background: #ca4040;
    }
    .blue-slide {
        background: #4390ee;
    }
    .orange-slide {
        background: #ff8604;
    }
    .green-slide {
        background: #49a430;
    }
    .pink-slide {
        background: #973e76;
    }
    .swiper-slide .title {
        font-style: italic;
        font-size: 42px;
        margin-top: 80px;
        margin-bottom: 0;
        line-height: 45px;
    }
    .pagination {
        position: absolute;
        z-index: 20;
        left: 10px;
        bottom: 10px;
    }
    .swiper-pagination-switch {
        display: inline-block;
        width: 8px;
        height: 8px;
        border-radius: 8px;
        background: #222;
        margin-right: 5px;
        opacity: 0.8;
        border: 1px solid #fff;
        cursor: pointer;
    }
    .swiper-visible-switch {
        background: #aaa;
    }
    .swiper-active-switch {
        background: #fff;
    }
    #widget-slideshow-home{
        float: left;
        position: relative;
        margin-top: -25px;
    }
    .swiper-slide div.img img{
        width: 220px;
        height: 250px;
    }

</style>
<div id="widget-slideshow-home">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide red-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/img/slider1-1.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide blue-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/img/slider1-2.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide orange-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/img/slider1-1.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide green-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/img/slider1-2.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide pink-slide">
                <div class="title"><a href="#">Slide 5</a></div>
            </div>
        </div>
        <div class="pagination"></div>
    </div>
</div>

<script src="<?php echo Mage::helper('link')->getSkinFrontend();?>swiper/js/idangerous.swiper-2.1.min.js"></script>
<script>
    var mySwiper = new Swiper('.swiper-container',{
        pagination: '.pagination',
        paginationClickable: true,
        slidesPerView: 3,
        loop: true
    })
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        function nextSlile() {
            $slideActive = jQuery('.pagination').find('.swiper-active-switch');
            if($slideActive.is(':last-child')){
                jQuery('.pagination').children().first().click();
            }
            else{
                $slideActive.next().click();
            }
        }
        setInterval(function(){
            nextSlile();
        },5000);
    });
</script>