<div id="widget-slideshow-home">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide red-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('featured/link')->getSkin();?>swiper/img/slider1-1.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide blue-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('featured/link')->getSkin();?>swiper/img/slider1-2.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide orange-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('featured/link')->getSkin();?>swiper/img/slider1-1.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide green-slide">
                <div class="img">
                    <a href="#">
                        <img src="<?php echo Mage::helper('featured/link')->getSkin();?>swiper/img/slider1-2.png">
                    </a>
                </div>
            </div>
            <div class="swiper-slide pink-slide">
                <div class="title"><a href="#">Slide 5</a></div>
            </div>
        </div>
        <div class="pagination"></div>
    </div>
</div>

<script src="<?php echo Mage::helper('featured/link')->getSkin();?>swiper/js/idangerous.swiper-2.1.min.js"></script>
<script>
    var mySwiper = new Swiper('.swiper-container',{
        pagination: '.pagination',
        paginationClickable: true,
        slidesPerView: 3,
        loop: true
    })
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        function nextSlile() {
            $slideActive = jQuery('.pagination').find('.swiper-active-switch');
            //alert($slideActive);
            if($slideActive.is(':last-child')){
                jQuery('.pagination').children().first().click();
            }
            else{
                $slideActive.next().click();
            }
        }
        /*$(document).on('click','#widget-slideshow-home',function(){
            alert(1212);
        });*/
        /*$(document).on
        ('click','.pagination span',function(){
            alert(12122);
        });*/
        setInterval(function(){
            nextSlile();
        },5000);
    });
</script>